name: Test CI/CD Pipeline

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7  # Specify the MySQL version you want
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Wait for MySQL to be ready
      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping -h "127.0.0.1" --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      # Export database connection settings for MySQL
      - name: Set up Django database settings
        run: |
          export DB_HOST=127.0.0.1
          export DB_NAME=testdb
          export DB_USER=testuser
          export DB_PASSWORD=testpassword
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          export AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME

      # Migrate the database
      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test

    env:
      DJANGO_SETTINGS_MODULE: your_project.settings
      DATABASE_URL: mysql://testuser:testpassword@127.0.0.1:3306/testdb
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
