# Generated by Django 5.1 on 2024-09-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_content', models.TextField()),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('s3_file_path', models.CharField(max_length=255)),
            ],
        ),
    ]
